{% set name = "xrayutilities" %}
{% set version = "1.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63fd635b1113601e163c29005d0ee1409e4551556f495fcef0a413c241fd232f

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - setuptools
    - python
    - h5py
    - scipy
  run:
    - h5py
    - lmfit
    - matplotlib-base
    - python
    - scipy

test:
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: https://xrayutilities.sourceforge.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: package for x-ray diffraction data evaluation
  doc_url: https://xrayutilities.sourceforge.io/
  dev_url: https://github.com/dkriegner/xrayutilities

extra:
  recipe-maintainers:
    - tschoonj
    - dkriegner
