{% set name = "xrayutilities" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a48d650d1087cabe8ff66cfe2b0f2448d9b35fa81bab566c52b1400962cb5e6

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - setuptools
    - python
    - h5py
    - scipy
  run:
    - h5py
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: https://xrayutilities.sourceforge.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: package for x-ray diffraction data evaluation
  doc_url: https://xrayutilities.sourceforge.io/
  dev_url: https://github.com/dkriegner/xrayutilities

extra:
  recipe-maintainers:
    - tschoonj
    - dkriegner
