{% set name = "xrayutilities" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2c5e7672b6b3e6152e2928bfabe58f5c2c8801df0f851dd37fd32a68fd45dd9

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - setuptools
    - python
    - h5py
    - scipy
  run:
    - h5py
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: https://xrayutilities.sourceforge.io
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL
  license_file: LICENSE.txt
  summary: package for x-ray diffraction data evaluation
  doc_url: https://xrayutilities.sourceforge.io/
  dev_url: https://github.com/dkriegner/xrayutilities

extra:
  recipe-maintainers:
    - tschoonj
    - dkriegner
