{% set name = "xrayutilities" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 06bf890461bd4493cd52bf687d142fde243ad370c2d5473fc3f1946a4930c9ca

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - scipy
    - h5py
    - pip
    - setuptools
    - python
  run:
    - h5py
    - numpy
    - python
    - setuptools
    - scipy

test:
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: "https://xrayutilities.sourceforge.io"
  license: "GNU General Public v2 or later (GPLv2+)"
  license_family: "GPL"
  license_file: "LICENSE.txt"
  summary: "package for x-ray diffraction data evaluation"
  doc_url: "https://xrayutilities.sourceforge.io/"
  dev_url: "https://github.com/dkriegner/xrayutilities"

extra:
  recipe-maintainers:
    - tschoonj
    - dkriegner
