{% set name = "xrayutilities" %}
{% set version = "1.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5da6262fedd92401226796ffed82c7696f0dfb9468e1bc1dab8bc4e4bd80d7e

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - meson-python
  host:
    - python
    - pip
    - meson-python
    - numpy
    - scipy
    - h5py
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py
    - lmfit
    - matplotlib-base

test:
  imports:
    - xrayutilities
    - xrayutilities.analysis
    - xrayutilities.io
    - xrayutilities.materials
    - xrayutilities.math
    - xrayutilities.simpack

about:
  home: https://xrayutilities.sourceforge.io
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: package for x-ray diffraction data evaluation
  doc_url: https://xrayutilities.sourceforge.io/
  dev_url: https://github.com/dkriegner/xrayutilities

extra:
  recipe-maintainers:
    - tschoonj
    - dkriegner
