travis:
  secure:
    BINSTAR_TOKEN: QS4g4R7HqQDQnvsNyFGUuedlafb3hx9pkMU2WNY54ehDzU/PLnyfamqNXyNOLO4QkEVfLJB4DGsrP3HXpZZFx9W52EfPDCVv1fQjYM6VCYE3wNSJurrnocGZUbvRWOTiYyh8+B0+hOJ8M0rYgxU59D6Q2J+KzfOvjSvneFAG5Wdbha94Bpr/XgX3K/YTi9Fh141jkunnSBKM6BFPK8YJe+GThLi913uCdOfxkiS7OGhnn03WU9RBBA5JRhYQbaxPLNP8pZarxjZV7pvMyA8kxWXnKSaeHkauozh1ijesjlkgIqg2ptNOeyWw/Mf9EGFDY5u2fqDOUHKQKv54snriYCaiL7ksQ7RhfRZnQTwexi0N1Ou6xoxFmA9M/fmJRDsjIto0uA4g3u0/f0S5jU2GuOn104+aXBcAPkP5nqj2U7hjMXWtPnWIAvE8g82ijw+hSHBNkbXSl3LY/529pxTxifQH2xMWlJrZi+FJTykMJJH/eEgN8EEhcF53l7bda1LDt5BywMPYRDB6ZXtiTfWXNNCaP9TxKRag2+GWb4hot/wQCoOhIRumsC+LbnBRhF1r6SzZ3CZR6eG9/rq5+04aPJbF+ahFuE+4TqKThAiRtCjOufmNXN6fdax6vAUC/eaWbkBGtjf1vG4UtXfuyV4fKnF9GmAS5oWjlXDvgziBShM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
